name: Update GitHub Profile

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py
        env:
          GITHUB_LOGIN: Soju06
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMITTER_NAME: Soju06
          COMMITTER_EMAIL: qlskssk@gmail.com
